# EDA

In [1]:
import collections

file_dict = collections.OrderedDict()
file_dict['../data/cft-train.zip'] = 'https://bucketeer-db1966c9-c9f8-427d-ae61-659a91a9fca7.s3.amazonaws.com/public/cft-train.zip'
file_dict['../data/cft-test.zip'] = 'https://bucketeer-db1966c9-c9f8-427d-ae61-659a91a9fca7.s3.amazonaws.com/public/cft-test.zip'

for file,url in file_dict.items():
    url_q = "'" + url + "'"
    ! wget --continue --no-check-certificate --no-proxy -O $file $url_q

--2018-10-08 09:40:50--  https://bucketeer-db1966c9-c9f8-427d-ae61-659a91a9fca7.s3.amazonaws.com/public/cft-train.zip
Resolving bucketeer-db1966c9-c9f8-427d-ae61-659a91a9fca7.s3.amazonaws.com (bucketeer-db1966c9-c9f8-427d-ae61-659a91a9fca7.s3.amazonaws.com)... 52.218.65.89
Connecting to bucketeer-db1966c9-c9f8-427d-ae61-659a91a9fca7.s3.amazonaws.com (bucketeer-db1966c9-c9f8-427d-ae61-659a91a9fca7.s3.amazonaws.com)|52.218.65.89|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 43643973 (42M) [application/zip]
Saving to: '../data/cft-train.zip'

../data/cft-train.z 100%[===================>]  41.62M  7.25MB/s    in 6.6s

2018-10-08 09:40:57 (6.33 MB/s) - '../data/cft-train.zip' saved [43643973/43643973]

--2018-10-08 09:40:57--  https://bucketeer-db1966c9-c9f8-427d-ae61-659a91a9fca7.s3.amazonaws.com/public/cft-test.zip
Resolving bucketeer-db1966c9-c9f8-427d-ae61-659a91a9fca7.s3.amazonaws.com (bucketeer-db1966c9-c9f8-427d-ae61-659a91a9fca7.s3.amazonaws.com)... 52.218.53.17
Connecting to bucketeer-db1966c9-c9f8-427d-ae61-659a91a9fca7.s3.amazonaws.com (bucketeer-db1966c9-c9f8-427d-ae61-659a91a9fca7.s3.amazonaws.com)|52.218.53.17|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 51007018 (49M) [application/zip]
Saving to: '../data/cft-test.zip'

../data/cft-test.zi 100%[===================>]  48.64M  6.88MB/s    in 7.4s

2018-10-08 09:41:05 (6.54 MB/s) - '../data/cft-test.zip' saved [51007018/51007018]

In [1]:
!unzip ../data/cft-train.zip -d ../data/
!unzip ../data/cft-test.zip -d ../data/

Archive:  ../data/cft-train.zip
  inflating: ../data/train.csv
Archive:  ../data/cft-test.zip
  inflating: ../data/test.csv

In [1]:
import pandas as pd

In [2]:
train_df = pd.read_csv('../data/train.csv')
test_df = pd.read_csv('../data/test.csv')

In [3]:
train_df.head()

,id,fullname,country,target,fullname_true
0,0,AKHMEDOV YGURIY,РОССИЯ,1,AKHMEDOV YURIY
1,1,ФОЗИЛОВ РАМИЛЬ ГУЛЛОВИЧ,РОССИЯ,1,ФОЗИЛОВ РАМИЛЬ ГУЛОВИЧ
2,2,ГОИБОВ АХЛИДДИН ШАМСУДИНОВИЧ,РОССИЯ,0,NaN
3,3,ХУСНЕУТДИНОВА МАРГАРИТА ФАХИМОВНА,РОССИЯ,1,ХУСНУТДИНОВА МАРГАРИТА ФАХИМОВНА
4,4,НОВОКШОНОВА ИННА ВЛАДИМИРОВНА,РОССИЯ,0,NaN

In [4]:
cns = train_df.country.value_counts()
top_countries = list(cns[cns>200].index)
train_df['country'] = train_df['country'].apply(lambda x: x if x in top_countries else 'OTHER')

In [5]:
train_df.country.value_counts()

РОССИЯ                   1342430
ТАДЖИКИСТАН               159770
УЗБЕКИСТАН                156234
КЫРГЫЗСТАН                 90851
КАЗАХСТАН                  53512
УКРАИНА                    39992
MOLDOVA                    31818
МОЛДОВА                    19789
RUS                        13618
UZBEKISTAN                 11441
BLR                         8609
OTHER                       7823
ГРУЗИЯ                      7476
КЫРГЫЗСКАЯ РЕСПУБЛИКА       5193
РОССИЙСКАЯ ФЕДЕРАЦИЯ        4474
АРМЕНИЯ                     4412
GEORGIA                     4315
UKR                         4254
АЗЕРБАЙДЖАН                 4246
АБХАЗИЯ                     3612
AZERBAIJAN                  3300
ПМР                         2728
БЕЛАРУСЬ                    2401
UZB                         1672
КИРГИЗИЯ                     836
TJK                          786
ANDIJON VIL                  737
AZE                          547
М.О.                         518
МОЛДОВА, РЕСПУБЛИКА          476
НИГЕРИЯ                      455
MDA                          399
РФ                           344
НАМАНГАН                     318
KGZ                          307
КР                           283
ШАХРИХОН                     260
ISRAEL                       221
НАВОИЙ                       220
ФИЛИППИНЫ                    214
KAZ                          213
Name: country, dtype: int64

In [23]:
pd.pivot_table(train_df,
               index='country',
               columns='target',
               values='fullname',
               aggfunc=pd.Series.nunique)

target                        0         1        2
country
ANDIJON VIL               338.0     383.0      1.0
AZE                       232.0     294.0      NaN
AZERBAIJAN               1561.0    1677.0      NaN
BLR                      3840.0    4486.0      NaN
GEORGIA                  1965.0    2222.0      4.0
ISRAEL                     91.0     112.0      NaN
KAZ                        96.0     110.0      NaN
KGZ                       137.0     162.0      1.0
MDA                       178.0     215.0      NaN
MOLDOVA                 14397.0   16508.0     23.0
OTHER                    4514.0    3100.0     59.0
RUS                      6024.0    7166.0      1.0
TJK                       337.0     415.0      2.0
UKR                      1833.0    2213.0      NaN
UZB                       764.0     870.0      NaN
UZBEKISTAN               5371.0    5926.0      2.0
АБХАЗИЯ                  1239.0    1489.0    713.0
АЗЕРБАЙДЖАН              1927.0    2174.0     13.0
АРМЕНИЯ                  1986.0    2140.0    214.0
БЕЛАРУСЬ                 1398.0     946.0     12.0
ГРУЗИЯ                   3361.0    3936.0      8.0
КАЗАХСТАН               23438.0   27815.0      6.0
КИРГИЗИЯ                  355.0     442.0      NaN
КР                        141.0     139.0      NaN
КЫРГЫЗСКАЯ РЕСПУБЛИКА    2358.0    2763.0      3.0
КЫРГЫЗСТАН              39925.0   47063.0    303.0
М.О.                      222.0     275.0      NaN
МОЛДОВА                 10387.0    8625.0    253.0
МОЛДОВА, РЕСПУБЛИКА       195.0     272.0      NaN
НАВОИЙ                     96.0     114.0      NaN
НАМАНГАН                  149.0     168.0      NaN
НИГЕРИЯ                   422.0      27.0      6.0
ПМР                      1225.0    1410.0      NaN
РОССИЙСКАЯ ФЕДЕРАЦИЯ     1933.0    2360.0      NaN
РОССИЯ                 528586.0  679924.0  38404.0
РФ                        162.0     169.0      3.0
ТАДЖИКИСТАН             70097.0   82444.0    661.0
УЗБЕКИСТАН              70839.0   81462.0    468.0
УКРАИНА                 18027.0   20543.0     22.0
ФИЛИППИНЫ                 204.0      10.0      NaN
ШАХРИХОН                  120.0     136.0      NaN

In [4]:
from sklearn.feature_extraction.text import CountVectorizer

In [5]:
cv = CountVectorizer(lowercase=False,
                     ngram_range=(1,1),
                     analyzer='char')

In [13]:
cv_test = CountVectorizer(lowercase=False,
                     ngram_range=(1,1),
                     analyzer='char')

In [8]:
# learn the vocabulary
cv.fit(list(train_df.fullname)+list(train_df.dropna().fullname_true))

CountVectorizer(analyzer='char', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=False, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [14]:
# test
cv_test.fit(test_df.fullname)

CountVectorizer(analyzer='char', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=False, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [24]:
set(symbol_df_test[symbol_df_test['count']>4000].char).difference(set(symbol_df[symbol_df['count']>4000].char))

set()

In [23]:
set(symbol_df[symbol_df['count']>4000].char).difference(set(symbol_df_test[symbol_df_test['count']>4000].char))

set()

In [16]:
set(cv_test.vocabulary_).difference(cv.vocabulary_)

{',', '/', '1', '2', '3', '4', '?', '[', '|', 'Є'}

In [15]:
set(cv.vocabulary_).difference(cv_test.vocabulary_)

{'5', '_', 'а', 'б', 'д', 'и', 'н', 'р', 'х'}

In [17]:
symbol_df_test = pd.DataFrame(columns=['char','count'])
for symbol in cv_test.vocabulary_:
    symbol_df_test = symbol_df_test.append(pd.DataFrame(data={
        'char':[symbol],
        'count':len(test_df[test_df.fullname.apply(lambda x: True if symbol in x else False)])
    }))

In [9]:
symbol_df = pd.DataFrame(columns=['char','count'])
for symbol in cv.vocabulary_:
    symbol_df = symbol_df.append(pd.DataFrame(data={
        'char':[symbol],
        'count':len(train_df[train_df.fullname.apply(lambda x: True if symbol in x else False)])
    }))

In [14]:
symbol_df.to_csv('symbols.csv')

In [46]:
train_df[train_df.fullname.apply(lambda x: True if 'а' in x else False)]

            id         fullname  country  target fullname_true
286958  286958  Шарбан Рихард -  МОЛДОВА       2           NaN

In [18]:
symbol_df_test['count'] = symbol_df_test['count'].astype(int)

In [20]:
symbol_df_test[symbol_df_test['count']<4000]

  char count
0    І    22
0    `    30
0    Ї     3
0    2     1
0    /     1
0    1     1
0    4     1
0    Є     3
0    ,     1
0    ?     1
0    3     1
0    [     1
0    |     1

In [18]:
symbol_df[symbol_df['count']<4000]

  char count
0    І    21
0    а     1
0    р     1
0    б     1
0    н     1
0    и     1
0    х     1
0    д     1
0    _     2
0    5     1
0    `     6
0    Ї     3

In [12]:
list(symbol_df[symbol_df['count']>4000].char.unique())

['A',
 'K',
 'H',
 'M',
 'E',
 'D',
 'O',
 'V',
 ' ',
 'Y',
 'G',
 'U',
 'R',
 'I',
 'Ф',
 'О',
 'З',
 'И',
 'Л',
 'В',
 'Р',
 'А',
 'М',
 'Ь',
 'Г',
 'У',
 'Ч',
 'Б',
 'Х',
 'Д',
 'Н',
 'Ш',
 'С',
 'Е',
 'Т',
 'К',
 'Ы',
 'П',
 'Ж',
 'Я',
 'Ю',
 'Й',
 'C',
 'S',
 'T',
 'L',
 'N',
 'Ъ',
 'Э',
 'Ц',
 'B',
 'J',
 'Щ',
 '-',
 '.',
 'Ё',
 'Z',
 'P',
 'X',
 'W',
 'F',
 "'",
 'Q']

In [43]:
len(cv.vocabulary_)

75

In [15]:
symbol_df

   char    count
0     A   219131
0     K   102485
0     H   122738
0     M   126047
0     E   135067
0     D   106453
0     O   180477
0     V   179476
0        1975506
0     Y    89749
0     G    65340
0     U   124653
0     R   174784
0     I   181841
0     Ф   220198
0     О  1622053
0     З   461391
0     И  1588955
0     Л  1249613
0     В  1689781
0     Р  1447465
0     А  1711205
0     М  1097509
0     Ь   327174
0     Г   565967
0     У   943420
0     Ч   951521
0     Б   762450
0     Х   605935
0     Д  1002928
..  ...      ...
0     L   127865
0     N   167101
0     Ъ    17875
0     Э    83410
0     Ц    58751
0     B    88956
0     J    42915
0     Щ    31887
0     -    13455
0     .     6258
0     Ё    47198
0     Z    61941
0     P    26159
0     X    27009
0     W     6394
0     F    28175
0     '     4122
0     Q    12121
0     І       21
0     а        1
0     р        1
0     б        1
0     н        1
0     и        1
0     х        1
0     д        1
0     _        2
0     5        1
0     `        6
0     Ї        3

[75 rows x 2 columns]

In [28]:
train_df.sample(n=20)

,id,fullname,country,target,fullname_true
1674722,1674722,DIDORA LARISA DMITRIYEVNA,УЗБЕКИСТАН,0,NaN
1330763,1330763,ЧИКУНОВ ВЯЧЕСЛАВ ГЕННАДТЬЕВИЧ,РОССИЯ,1,ЧИКУНОВ ВЯЧЕСЛАВ ГЕННАДЬЕВИЧ
1900680,1900680,МОЗОЛЬ РОМАН АЛЕКСАНДРОВИЧ,РОССИЯ,0,NaN
583663,583663,ТРИФАН ПЁЬТР,MOLDOVA,1,ТРИФАН ПЁТР
844500,844500,ХОЖИЕВ МАХМАДЮСУФ КАМОЛИЛИНОВИЧ,РОССИЯ,1,ХОЖИЕВ МАХМАДЮСУФ КАМОЛИДИНОВИЧ
550601,550601,TASHTEMIROVA MAKSUDAXON AMANOVNA,УЗБЕКИСТАН,0,NaN
816330,816330,МУХАММАДИЕВ БАХТИЁР ХУДОЙКУЛОВИЧ,ТАДЖИКИСТАН,0,NaN
1147217,1147217,СИЗОВ СЕРГЕЙ ВЛАДИМИРОВИЧ,РОССИЯ,0,NaN
422218,422218,ЗЕЛЕНКО АННА ЮРЬЕВНА,УКРАИНА,0,NaN
14579,14579,КАМБАРОВ БОТИРЖОН ЖУМАБОЕВИЧ,РОССИЯ,0,NaN
1536143,1536143,MAMADJONOV ASRORBEK,РОССИЯ,0,NaN
891636,891636,МИРЗАХОДЖАЕВ БУРХОН МУЛАЖАНЯОВИЧ,РОССИЯ,1,МИРЗАХОДЖАЕВ БУРХОН МУЛАЖАНОВИЧ
60459,60459,БАСТРАКОВА ТАТЬЯНА ПЕТРОВНА,РОССИЯ,0,NaN
97886,97886,АЛЕСКЕРОВ САХИЛ МАЛИК ОГЛЫ,РОССИЯ,0,NaN
347487,347487,ЗЫКОВА ЕЛЕНЪ РОБЕРТОВНА,РОССИЯ,1,ЗЫКОВА ЕЛЕНА РОБЕРТОВНА
1468316,1468316,TADEVOSYAN SAMVEL,РОССИЯ,0,NaN
281091,281091,АМИНОВ САЛИМБОЙ АЛИМЛОВИЧ,РОССИЯ,1,АМИНОВ САЛИМБОЙ АЛИМОВИЧ
1175767,1175767,АБРИЕВ ШЕРЗОД ВКОБИЛЖОНОВИЧ,УЗБЕКИСТАН,1,АБРИЕВ ШЕРЗОД КОБИЛЖОНОВИЧ
810551,810551,АЗИЗОВА САБОХАТ АСАДУЛЛОЕВНА,ТАДЖИКИСТАН,0,NaN
1946210,1946210,ЭГЕМНАЗАРОВ ЕГТР КАРИМОВИЧ,РОССИЯ,1,ЭГЕМНАЗАРОВ ЕГОР КАРИМОВИЧ

# Dataset class

In [1]:
import pandas as pd
from pytorch.symbols import symbol_list

In [2]:
train_df = pd.read_csv('../data/train.csv')
test_df = pd.read_csv('../data/test.csv')

In [13]:
(train_df.fullname.apply(lambda x: len(x)).max(),
train_df.fullname_true.dropna().apply(lambda x: len(x)).max(),
test_df.fullname.apply(lambda x: len(x)).max())

(92, 89, 83)

In [10]:
train_df.head(),test_df.head()

(   id                           fullname country  target  \
 0   0                    AKHMEDOV YGURIY  РОССИЯ       1
 1   1            ФОЗИЛОВ РАМИЛЬ ГУЛЛОВИЧ  РОССИЯ       1
 2   2       ГОИБОВ АХЛИДДИН ШАМСУДИНОВИЧ  РОССИЯ       0
 3   3  ХУСНЕУТДИНОВА МАРГАРИТА ФАХИМОВНА  РОССИЯ       1
 4   4      НОВОКШОНОВА ИННА ВЛАДИМИРОВНА  РОССИЯ       0

                       fullname_true
 0                    AKHMEDOV YURIY
 1            ФОЗИЛОВ РАМИЛЬ ГУЛОВИЧ
 2                               NaN
 3  ХУСНУТДИНОВА МАРГАРИТА ФАХИМОВНА
 4                               NaN  ,
    id                        fullname     country
 0   0  ХУДАШКУРОВА ГУЛЗХОДА БЕРДИЕВНА  УЗБЕКИСТАН
 1   1          СВЕЖЕТЬФЛОГИСТОН АРСЕН      РОССИЯ
 2   2        ГУЛОМОВА СОЖИДА САНАЕВНА  УЗБЕКИСТАН
 3   3   КАМПЫШЕВА ГУЛЯИМ БЕЙСЕМБАЕВНА   КАЗАХСТАН
 4   4              OROSUMEBTOV MIRLAN      РОССИЯ)

In [7]:
cns = train_df.country.value_counts()
top_countries = list(cns[cns>100].index)
train_df['country'] = train_df['country'].apply(lambda x: x if x in top_countries else 'OTHER')
test_df['country'] = test_df['country'].apply(lambda x: x if x in top_countries else 'OTHER')

cn_dict = dict(zip(sorted(list(train_df['country'].unique())),
                   range(train_df['country'].nunique())))

train_df['country'] = train_df['country'].apply(lambda x: cn_dict[x])
test_df['country'] = test_df['country'].apply(lambda x: cn_dict[x])

In [11]:
train_df.country.value_counts()

44    1342430
48     159770
51     156234
34      90851
28      53512
52      39992
11      31818
36      19789
13      13618
18      11441
4        8609
25       7476
12       5671
33       5193
43       4474
21       4412
5        4315
16       4254
20       4246
19       3612
3        3300
41       2728
22       2401
17       1672
30        836
15        786
0         737
2         547
35        518
37        476
40        455
10        399
46        344
39        318
9         307
32        283
54        260
6         221
38        220
53        214
7         213
14        191
29        185
26        184
8         183
24        178
27        178
1         161
23        158
50        136
45        133
49        129
31        116
47        114
42        106
Name: country, dtype: int64

In [9]:
len(cn_dict)

55

In [5]:
cns_test = test_df.country.value_counts()
top_countries_test = list(cns_test[cns_test>200].index)
# train_df['country'] = train_df['country'].apply(lambda x: x if x in top_countries else 'OTHER')

In [35]:
train_df.shape,test_df.shape

((1991104, 5), (2767639, 3))

In [6]:
cns_test[cns_test.index.isin(set(top_countries_test).difference(set(top_countries)))]

Series([], Name: country, dtype: int64)

In [25]:
set(top_countries).difference(set(top_countries_test))

set()

In [23]:
cns_test

РОССИЯ                                        1828080
УЗБЕКИСТАН                                     230258
ТАДЖИКИСТАН                                    229040
КЫРГЫЗСТАН                                     129599
КАЗАХСТАН                                       77120
УКРАИНА                                         57843
MOLDOVA                                         46253
МОЛДОВА                                         28605
RUS                                             20005
UZBEKISTAN                                      16864
BLR                                             12531
ГРУЗИЯ                                          10894
КЫРГЫЗСКАЯ РЕСПУБЛИКА                            7702
АРМЕНИЯ                                          6533
GEORGIA                                          6477
РОССИЙСКАЯ ФЕДЕРАЦИЯ                             6346
UKR                                              6004
АЗЕРБАЙДЖАН                                      5907
АБХАЗИЯ                                          5122
AZERBAIJAN                                       4733
ПМР                                              3905
БЕЛАРУСЬ                                         3584
UZB                                              2421
КИРГИЗИЯ                                         1237
TJK                                              1143
ANDIJON VIL                                      1037
М.О.                                              768
AZE                                               766
МОЛДОВА, РЕСПУБЛИКА                               724
НИГЕРИЯ                                           706
                                               ...
ТАФ СУЛТОН                                          1
KARAKALPAKSTAN                                      1
КСИАТКУЗ                                            1
TIPLETESTI                                          1
ФАЙЗАБА                                             1
РОССИЯ,ПЕНЗЕНСКАЯ ОБЛ.,ГОРОДИЩЕНСКИЙ РАЙОН          1
ЦУЗБ                                                1
МУМИНАБАД                                           1
РОИССИЯ                                             1
ФАЙЗАБАД                                            1
ШАХРИХОН ТУМАН Ю ШАХРИХОН                           1
ЖАМБЫЛСКАЯ ОБЛ.                                     1
ИТАЭТ                                               1
РВ                                                  1
РОССИЯ ДАГЕСТАН                                     1
КАЗАХСТАН"                                          1
YANGIBOZOR                                          1
БУТАН                                               1
КЫРГЫЗСТАНКАДАМЖАЙ                                  1
РОССИЯ ТУЛЬСКАЯ ОБЛАСТЬ                             1
ИД                                                  1
ТВА                                                 1
НАРЫН                                               1
ШАХРИХОН ТУМАНИ КОРАБУЙИН КФЙ                       1
САТ                                                 1
ЙТА                                                 1
ДЖЭД                                                1
НИШОН ТУМАНИ                                        1
ОВД Г ПЕНДЖИКЕНТ                                    1
РОССИЯ РЕСПУБЛИКА ТАТАРСТАН                         1
Name: country, Length: 1644, dtype: int64

In [20]:
top_countries

['РОССИЯ',
 'ТАДЖИКИСТАН',
 'УЗБЕКИСТАН',
 'КЫРГЫЗСТАН',
 'КАЗАХСТАН',
 'УКРАИНА',
 'MOLDOVA',
 'МОЛДОВА',
 'RUS',
 'UZBEKISTAN',
 'BLR',
 'ГРУЗИЯ',
 'КЫРГЫЗСКАЯ РЕСПУБЛИКА',
 'РОССИЙСКАЯ ФЕДЕРАЦИЯ',
 'АРМЕНИЯ',
 'GEORGIA',
 'UKR',
 'АЗЕРБАЙДЖАН',
 'АБХАЗИЯ',
 'AZERBAIJAN',
 'ПМР',
 'БЕЛАРУСЬ',
 'UZB',
 'КИРГИЗИЯ',
 'TJK',
 'ANDIJON VIL',
 'AZE',
 'М.О.',
 'МОЛДОВА, РЕСПУБЛИКА',
 'НИГЕРИЯ',
 'MDA',
 'РФ',
 'НАМАНГАН',
 'KGZ',
 'КР',
 'ШАХРИХОН',
 'ISRAEL',
 'НАВОИЙ',
 'ФИЛИППИНЫ',
 'KAZ']

In [36]:
train_df[train_df.target.isin([1])]

,id,fullname,country,target,fullname_true
0,0,AKHMEDOV YGURIY,44,1,AKHMEDOV YURIY
1,1,ФОЗИЛОВ РАМИЛЬ ГУЛЛОВИЧ,44,1,ФОЗИЛОВ РАМИЛЬ ГУЛОВИЧ
3,3,ХУСНЕУТДИНОВА МАРГАРИТА ФАХИМОВНА,44,1,ХУСНУТДИНОВА МАРГАРИТА ФАХИМОВНА
5,5,МЕДЕТБЕК КЫЗЫ МАПАБАТ,34,1,МЕДЕТБЕК КЫЗЫ МАХАБАТ
7,7,ТИРКАШЕПВ МАШРАБ УСМОНОВИЧ,44,1,ТИРКАШЕВ МАШРАБ УСМОНОВИЧ
8,8,НАЛТАКЯН ГАМЬЛЕТ АЛЬБЕРТОВИЧ,13,1,НАЛТАКЯН ГАМЛЕТ АЛЬБЕРТОВИЧ
9,9,ГНИГОРЯН АННА ЛЕОНИДОВНА,44,1,ГРИГОРЯН АННА ЛЕОНИДОВНА
14,14,МУНРЗАБАЕВ УЗАК,12,1,МУРЗАБАЕВ УЗАК
15,15,CIUMAC SVETLANA IVCAN,11,1,CIUMAC SVETLANA IVAN
16,16,ЛУКЬЯНЧУК МАРИНА СЕРГЕЕВНВА,44,1,ЛУКЬЯНЧУК МАРИНА СЕРГЕЕВНА
18,18,АТКИЯЕВ ОЙЕБК ИБОДУЛОЕВИЧ,44,1,АТКИЯЕВ ОЙБЕК ИБОДУЛОЕВИЧ
19,19,САФАРОВ МУЗАФФАМР,44,1,САФАРОВ МУЗАФФАР
20,20,ЗАЙДУЛЕОВА РАЪНОГУЛ ЗОХИРОВНА,48,1,ЗАЙДУЛОЕВА РАЪНОГУЛ ЗОХИРОВНА
21,21,ЧАПЛЫГИН ВЕНИАМИНГ АЛЕКСАНДРОВИЧ,44,1,ЧАПЛЫГИН ВЕНИАМИН АЛЕКСАНДРОВИЧ
24,24,МРВСИСЯН СМБАТ АРСЕНОВИЧ,44,1,МОВСИСЯН СМБАТ АРСЕНОВИЧ
25,25,УММАРОВА МУНИСА ИСМАТОВНА,44,1,УМАРОВА МУНИСА ИСМАТОВНА
26,26,БАЛАН ШТЙФАН,11,1,БАЛАН ШТЕФАН
28,28,КАРИМОВ ТУХТАСИН ГАЗИЕВИС,44,1,КАРИМОВ ТУХТАСИН ГАЗИЕВИЧ
29,29,NLOROV ERKIN,44,1,NOROV ERKIN
32,32,АГРОНОМОВА СВЕТЛАНА ВИКТОРОВН,44,1,АГРОНОМОВА СВЕТЛАНА ВИКТОРОВНА
33,33,ЗАХАРИКОВАИРИНА АНАТОЛЬЕВНА,44,1,ЗАХАРИКОВА ИРИНА АНАТОЛЬЕВНА
34,34,SOBITOV SHERALK,51,1,SOBITOV SHERALI
39,39,ПУЛИКОВ АРНКАДИЙ АЛЕКСАНДРОВИЧ,44,1,ПУЛИКОВ АРКАДИЙ АЛЕКСАНДРОВИЧ
40,40,МУРАТОВА РОЗМЛИЯ МАТНАЗАРОВНА,44,1,МУРАТОВА РОЗАЛИЯ МАТНАЗАРОВНА
42,42,КРАСНОРПИСЦЕВА ТАТЬЯНА ИВАНОВНА,44,1,КРАСНОПИСЦЕВА ТАТЬЯНА ИВАНОВНА
45,45,РАМАЗАНОВА ФАТИМА МАХМДУОВНА,44,1,РАМАЗАНОВА ФАТИМА МАХМУДОВНА
46,46,ГУСАКОУА НАТАЛЬЯ АНАТОЛЬЕВНА,44,1,ГУСАКОВА НАТАЛЬЯ АНАТОЛЬЕВНА
47,47,ДЖОМАХМАДОВ БАХРИДДИН ТШОДЖИДИНОВИЧ,48,1,ДЖОМАХМАДОВ БАХРИДДИН ТОДЖИДИНОВИЧ
49,49,БАРКОВА ЮЛИЯ АЛЬБЕНТОВНА,44,1,БАРКОВА ЮЛИЯ АЛЬБЕРТОВНА
51,51,АЗТИМОВ ХУМОЮН АБДУРАУФОВИЧ,48,1,АЗИМОВ ХУМОЮН АБДУРАУФОВИЧ
...,...,...,...,...,...
1991053,1991053,ПУШКИН ДМИТРИЙ СЕРГЕЕУИЧ,51,1,ПУШКИН ДМИТРИЙ СЕРГЕЕВИЧ
1991054,1991054,ХУСИНОВ ШАСХНАЗАР РАХИМОВИЧ,44,1,ХУСИНОВ ШАХНАЗАР РАХИМОВИЧ
1991055,1991055,НОТРОВ МУХИДДИН ЭРГАШЕВИЧ,44,1,НОРОВ МУХИДДИН ЭРГАШЕВИЧ
1991058,1991058,МАГРТЫНОВА ЕЛЕНА НИКОЛАЕВНА,44,1,МАРТЫНОВА ЕЛЕНА НИКОЛАЕВНА
1991060,1991060,ВАЛИЕВ ХАСАНРАДЖАБОВИЧ,44,1,ВАЛИЕВ ХАСАН РАДЖАБОВИЧ
1991061,1991061,ЗАБРОВСКАЯ НАЛИЯ КАЛЕННИКОВНА,48,1,ЗАБРОВСКАЯ НАИЛЯ КАЛЕННИКОВНА
1991062,1991062,КУРГБОНОВ БАХТОВАР МУРОДОВИЧ,44,1,КУРБОНОВ БАХТОВАР МУРОДОВИЧ
1991063,1991063,KOCHKOROVA ZAMIRAKHKON,44,1,KOCHKOROVA ZAMIRAKHON
1991065,1991065,БАЛАМЕДОВАЕКАТЕРИНВ ЛЕОНИДОВНА,44,1,БАЛАМЕДОВА ЕКАТЕРИНА ЛЕОНИДОВНА
1991067,1991067,КАБОЗОВА МИРА ТУРУСБЕКОВНА,44,1,КАРБОЗОВА МИРА ТУРУСБЕКОВНА
1991071,1991071,ИСУФОВ ЗУХАМАДМУРОД ХАСАНОВИЧ,48,1,ИСУФОВ МУХАМАДМУРОД ХАСАНОВИЧ
1991073,1991073,ИВАНОВА АННА МИАЙЛОВНА,44,1,ИВАНОВА АННА МИХАЙЛОВНА
1991074,1991074,ЯКУБОАА ЧЫНАРА ЗУХРИДИНОВНА,44,1,ЯКУБОВА ЧЫНАРА ЗУХРИДИНОВНА
1991075,1991075,ДОДОЕВ БЕГА РУСТАМОВИЧ,18,1,ДОДОЕВ БЕГАМ РУСТАМОВИЧ
1991076,1991076,МАЧОРОВА МАРИЯ АЛЕКСАНЩРОВНА,44,1,МАЧОРОВА МАРИЯ АЛЕКСАНДРОВНА
1991078,1991078,ГУСЕЙНОВ НИЫЗАМАДДИН САХИБ ОГЛЫ,44,1,ГУСЕЙНОВ НИЗАМАДДИН САХИБ ОГЛЫ
1991080,1991080,ВАРДАНОВАЕ ЗОЯ,44,1,ВАРДАНОВА ЗОЯ
1991083,1991083,РАХМАНОВ АЗАД АФРАШИМ ОГОЛЫ,44,1,РАХМАНОВ АЗАД АФРАШИМ ОГЛЫ
1991084,1991084,МАМОНОВА МАРРНА ЕВГЕНЬЕВНА,52,1,МАМОНОВА МАРИНА ЕВГЕНЬЕВНА
1991086,1991086,ХАКИМОВ ДЖОЫВИДОН ХАКИМОВИЧ,48,1,ХАКИМОВ ДЖОВИДОН ХАКИМОВИЧ
1991087,1991087,ГАФУРОВА ОЙТУЛО НКРЗУЛОЕВНА,48,1,ГАФУРОВА ОЙТУЛО НАРЗУЛОЕВНА
1991088,1991088,МАРТИРОСЯН СЕРИНЕ ЭДБУАРДОВНА,44,1,МАРТИРОСЯН СЕРИНЕ ЭДУАРДОВНА
1991089,1991089,ЛЕОТТЬЕВА СВЕТЛАНА ИГОРЕВНА,44,1,ЛЕОНТЬЕВА СВЕТЛАНА ИГОРЕВНА
1991090,1991090,ХИСМОНОВ ХАСАН САРДОРОУИЧ,44,1,ХИСМОНОВ ХАСАН САРДОРОВИЧ
1991092,1991092,ШОЗИЕВ ХОМИД УЗБЕКОВИЧ,44,1,ШОДИЕВ ХОМИД УЗБЕКОВИЧ
1991097,1991097,AGHAJANYAN VCAZGEN,44,1,AGHAJANYAN VAZGEN
1991098,1991098,ДБОЙКУ ЕКАТЕРИНА ВИТАЛЬЕВНА,52,1,БОЙКУ ЕКАТЕРИНА ВИТАЛЬЕВНА
1991099,1991099,ХАПЛИМОВ САТТАР АКРАМОВИЧ,44,1,ХАЛИМОВ САТТАР АКРАМОВИЧ
1991101,1991101,ЗОХИДОВ МУХТОРХОН ГУФРОНОВИЧС,44,1,ЗОХИДОВ МУХТОРХОН ГУФРОНОВИЧ
1991102,1991102,КОНОНОВ АНЮДРЕЙПЕТРОВИЧ,44,1,КОНОНОВ АНДРЕЙ ПЕТРОВИЧ

In [31]:
train_df.loc[pd.isnull(train_df.fullname_true),'fullname_true'] = train_df.loc[pd.isnull(train_df.fullname_true),'fullname']

In [21]:
test_df.country.value_counts()

РОССИЯ                                        1828080
УЗБЕКИСТАН                                     230258
ТАДЖИКИСТАН                                    229040
КЫРГЫЗСТАН                                     129599
КАЗАХСТАН                                       77120
УКРАИНА                                         57843
MOLDOVA                                         46253
МОЛДОВА                                         28605
RUS                                             20005
UZBEKISTAN                                      16864
BLR                                             12531
ГРУЗИЯ                                          10894
КЫРГЫЗСКАЯ РЕСПУБЛИКА                            7702
АРМЕНИЯ                                          6533
GEORGIA                                          6477
РОССИЙСКАЯ ФЕДЕРАЦИЯ                             6346
UKR                                              6004
АЗЕРБАЙДЖАН                                      5907
АБХАЗИЯ                                          5122
AZERBAIJAN                                       4733
ПМР                                              3905
БЕЛАРУСЬ                                         3584
UZB                                              2421
КИРГИЗИЯ                                         1237
TJK                                              1143
ANDIJON VIL                                      1037
М.О.                                              768
AZE                                               766
МОЛДОВА, РЕСПУБЛИКА                               724
НИГЕРИЯ                                           706
                                               ...
ТАФ СУЛТОН                                          1
KARAKALPAKSTAN                                      1
КСИАТКУЗ                                            1
TIPLETESTI                                          1
ФАЙЗАБА                                             1
РОССИЯ,ПЕНЗЕНСКАЯ ОБЛ.,ГОРОДИЩЕНСКИЙ РАЙОН          1
ЦУЗБ                                                1
МУМИНАБАД                                           1
РОИССИЯ                                             1
ФАЙЗАБАД                                            1
ШАХРИХОН ТУМАН Ю ШАХРИХОН                           1
ЖАМБЫЛСКАЯ ОБЛ.                                     1
ИТАЭТ                                               1
РВ                                                  1
РОССИЯ ДАГЕСТАН                                     1
КАЗАХСТАН"                                          1
YANGIBOZOR                                          1
БУТАН                                               1
КЫРГЫЗСТАНКАДАМЖАЙ                                  1
РОССИЯ ТУЛЬСКАЯ ОБЛАСТЬ                             1
ИД                                                  1
ТВА                                                 1
НАРЫН                                               1
ШАХРИХОН ТУМАНИ КОРАБУЙИН КФЙ                       1
САТ                                                 1
ЙТА                                                 1
ДЖЭД                                                1
НИШОН ТУМАНИ                                        1
ОВД Г ПЕНДЖИКЕНТ                                    1
РОССИЯ РЕСПУБЛИКА ТАТАРСТАН                         1
Name: country, Length: 1644, dtype: int64

In [42]:
r_tuple = dset.__getitem__(0)

In [49]:
r_tuple[1]

tensor([[  63,   67],
        [   4,   68],
        [  14,   69],
        [  11,   70],
        [  16,   71],
        [   8,   72],
        [   7,   73],
        [  18,   74],
        [  25,   75],
        [   0,   76],
        [  28,   77],
        [  10,   78],
        [  24,   79],
        [  21,   80],
        [  12,   81],
        [  28,   82],
        [  66,   83],
        [  64,   84],
        [  64,   85],
        [  64,   86],
        [  64,   87],
        [  64,   88],
        [  64,   89],
        [  64,   90],
        [  64,   91],
        [  64,   92],
        [  64,   93],
        [  64,   94],
        [  64,   95],
        [  64,   96],
        [  64,   97],
        [  64,   98],
        [  64,   99],
        [  64,  100],
        [  64,  101],
        [  64,  102],
        [  64,  103],
        [  64,  104],
        [  64,  105],
        [  64,  106],
        [  64,  107],
        [  64,  108],
        [  64,  109],
        [  64,  110],
        [  64,  111],
        [  64,  112],
        [  64,  113],
        [  64,  114],
        [  64,  115],
        [  64,  116],
        [  64,  117],
        [  64,  118],
        [  64,  119],
        [  64,  120],
        [  64,  121],
        [  64,  122],
        [  64,  123],
        [  64,  124],
        [  64,  125],
        [  64,  126],
        [  64,  127],
        [  64,  128],
        [  64,  129],
        [  64,  130],
        [  64,  131],
        [  64,  132],
        [  64,  133],
        [  64,  134],
        [  64,  135],
        [  64,  136],
        [  64,  137],
        [  64,  138],
        [  64,  139],
        [  64,  140],
        [  64,  141],
        [  64,  142],
        [  64,  143],
        [  64,  144],
        [  64,  145],
        [  64,  146],
        [  64,  147],
        [  64,  148],
        [  64,  149],
        [  64,  150],
        [  64,  151],
        [  64,  152],
        [  64,  153],
        [  64,  154],
        [  64,  155],
        [  64,  156],
        [  64,  157],
        [  64,  158],
        [  64,  159],
        [  64,  160],
        [  64,  161],
        [  64,  162],
        [  64,  163],
        [  64,  164],
        [  64,  165],
        [  64,  166]])

In [ ]:
[name,
                            name_processed.long(),
                            name_mmb.float(),
                            gt_name,
                            gt_name_processed,
                            gt_name_mmb,
                            target,
                            country]

In [43]:
len(r_tuple)

8

In [41]:
dset = MisprintDataset()

_start_ tag added to the dataset with index 63
_pad_ tag added to the dataset with index 64
_unk_ tag added to the dataset with index 65
_classify_ tag added to the dataset with index 66
_pos0_ tag added to the dataset with index 67
_pos1_ tag added to the dataset with index 68
_pos2_ tag added to the dataset with index 69
_pos3_ tag added to the dataset with index 70
_pos4_ tag added to the dataset with index 71
_pos5_ tag added to the dataset with index 72
_pos6_ tag added to the dataset with index 73
_pos7_ tag added to the dataset with index 74
_pos8_ tag added to the dataset with index 75
_pos9_ tag added to the dataset with index 76
_pos10_ tag added to the dataset with index 77
_pos11_ tag added to the dataset with index 78
_pos12_ tag added to the dataset with index 79
_pos13_ tag added to the dataset with index 80
_pos14_ tag added to the dataset with index 81
_pos15_ tag added to the dataset with index 82
_pos16_ tag added to the dataset with index 83
_pos17_ tag added to the dataset with index 84
_pos18_ tag added to the dataset with index 85
_pos19_ tag added to the dataset with index 86
_pos20_ tag added to the dataset with index 87
_pos21_ tag added to the dataset with index 88
_pos22_ tag added to the dataset with index 89
_pos23_ tag added to the dataset with index 90
_pos24_ tag added to the dataset with index 91
_pos25_ tag added to the dataset with index 92
_pos26_ tag added to the dataset with index 93
_pos27_ tag added to the dataset with index 94
_pos28_ tag added to the dataset with index 95
_pos29_ tag added to the dataset with index 96
_pos30_ tag added to the dataset with index 97
_pos31_ tag added to the dataset with index 98
_pos32_ tag added to the dataset with index 99
_pos33_ tag added to the dataset with index 100
_pos34_ tag added to the dataset with index 101
_pos35_ tag added to the dataset with index 102
_pos36_ tag added to the dataset with index 103
_pos37_ tag added to the dataset with index 104
_pos38_ tag added to the dataset with index 105
_pos39_ tag added to the dataset with index 106
_pos40_ tag added to the dataset with index 107
_pos41_ tag added to the dataset with index 108
_pos42_ tag added to the dataset with index 109
_pos43_ tag added to the dataset with index 110
_pos44_ tag added to the dataset with index 111
_pos45_ tag added to the dataset with index 112
_pos46_ tag added to the dataset with index 113
_pos47_ tag added to the dataset with index 114
_pos48_ tag added to the dataset with index 115
_pos49_ tag added to the dataset with index 116
_pos50_ tag added to the dataset with index 117
_pos51_ tag added to the dataset with index 118
_pos52_ tag added to the dataset with index 119
_pos53_ tag added to the dataset with index 120
_pos54_ tag added to the dataset with index 121
_pos55_ tag added to the dataset with index 122
_pos56_ tag added to the dataset with index 123
_pos57_ tag added to the dataset with index 124
_pos58_ tag added to the dataset with index 125
_pos59_ tag added to the dataset with index 126
_pos60_ tag added to the dataset with index 127
_pos61_ tag added to the dataset with index 128
_pos62_ tag added to the dataset with index 129
_pos63_ tag added to the dataset with index 130
_pos64_ tag added to the dataset with index 131
_pos65_ tag added to the dataset with index 132
_pos66_ tag added to the dataset with index 133
_pos67_ tag added to the dataset with index 134
_pos68_ tag added to the dataset with index 135
_pos69_ tag added to the dataset with index 136
_pos70_ tag added to the dataset with index 137
_pos71_ tag added to the dataset with index 138
_pos72_ tag added to the dataset with index 139
_pos73_ tag added to the dataset with index 140
_pos74_ tag added to the dataset with index 141
_pos75_ tag added to the dataset with index 142
_pos76_ tag added to the dataset with index 143
_pos77_ tag added to the dataset with index 144
_pos78_ tag added to the dataset with index 145
_pos79_ tag added to the dataset with index 146
_pos80_ tag added to the dataset with index 147
_pos81_ tag added to the dataset with index 148
_pos82_ tag added to the dataset with index 149
_pos83_ tag added to the dataset with index 150
_pos84_ tag added to the dataset with index 151
_pos85_ tag added to the dataset with index 152
_pos86_ tag added to the dataset with index 153
_pos87_ tag added to the dataset with index 154
_pos88_ tag added to the dataset with index 155
_pos89_ tag added to the dataset with index 156
_pos90_ tag added to the dataset with index 157
_pos91_ tag added to the dataset with index 158
_pos92_ tag added to the dataset with index 159
_pos93_ tag added to the dataset with index 160
_pos94_ tag added to the dataset with index 161
_pos95_ tag added to the dataset with index 162
_pos96_ tag added to the dataset with index 163
_pos97_ tag added to the dataset with index 164
_pos98_ tag added to the dataset with index 165
_pos99_ tag added to the dataset with index 166

In [40]:
import torch
import numpy as np
import pandas as pd
import torch.utils.data as data
from pytorch.symbols import symbol_list
from sklearn.model_selection import StratifiedKFold

symbol_dict = dict(zip(sorted(symbol_list),
                       range(0,len(symbol_list))))

class MisprintDataset(data.Dataset):
    def __init__(self,
                 train_df_path='../data/train.csv',
                 test_df_path='../data/test.csv',
                 symbol_dict=symbol_dict, # only symbols in the pre-defined dict
                 mode='train', # train, val or test
                 
                 max_len=100, # good enough length for attention
                 fold=0,
                 
                 target_column='target',
                 name_column='fullname',
                 gt_name_column='fullname_true',
                 country_column='country',
                 
                 random_state=42,
                 return_meta=False,
                 return_string=False):
        
        train_df = pd.read_csv(train_df_path)
        test_df = pd.read_csv(test_df_path)
        self.s2i = symbol_dict
        
        self.mode = mode
        self.fold = fold
        self.max_len = max_len
        self.random_state = random_state

        
        cns = train_df.country.value_counts()
        top_countries = list(cns[cns>100].index)
        
        train_df['country'] = train_df['country'].apply(lambda x: x if x in top_countries else 'OTHER')
        train_df.loc[pd.isnull(train_df.fullname_true),
                     'fullname_true'] = train_df.loc[pd.isnull(train_df.fullname_true),
                                                     'fullname']
        
        test_df['country'] = test_df['country'].apply(lambda x: x if x in top_countries else 'OTHER')

        self.cn_dict = dict(zip(sorted(list(train_df['country'].unique())),
                                range(train_df['country'].nunique())))

        train_df['country'] = train_df['country'].apply(lambda x: self.cn_dict[x])
        test_df['country'] = test_df['country'].apply(lambda x: self.cn_dict[x])        
        

        self.train_names = train_df[name_column].values
        self.train_gt_names = train_df[gt_name_column].values
        self.train_targets = train_df[target_column].values
        self.train_countries = train_df[country_column].values
        
        self.test_names = test_df[name_column].values
        self.test_countries = test_df[country_column].values

        del train_df,test_df
        
        # check that unique tokens are present
        # otherwise add them to the dataset
        
        for new_tag in ['_start_','_pad_','_unk_','_classify_']:
            if new_tag not in self.s2i:
                self.s2i[new_tag] = len(self.s2i)
                print('{} tag added to the dataset with index {}'.format(new_tag,
                                                                         len(self.s2i)-1))               
        self.clf_token = self.s2i['_classify_']
        self.vocab_len = len(self.s2i)     
            
        # add position embeddings
        for i in range(0,self.max_len):
            pos_emb = '_pos{}_'.format(i)
            if pos_emb not in self.s2i:
                self.s2i[pos_emb] = len(self.s2i)
                print('{} tag added to the dataset with index {}'.format(pos_emb,
                                                                     len(self.s2i)-1))                   

        skf = StratifiedKFold(n_splits = 4,
                              shuffle = True,
                              random_state = self.random_state)

        f1, f2, f3, f4 = skf.split(list(self.train_names),
                                   list(self.train_countries))
 
        folds = [f1, f2, f3, f4]
        self.train_idx = folds[self.fold][0]
        self.val_idx = folds[self.fold][1] 

    def __getitem__(self, idx):
        if self.mode == 'train':
            _idx = self.train_idx[idx]
        elif self.mode == 'val':
            _idx = self.val_idx[idx]

        if self.mode in ('train','val'):
            name,gt_name,target,country = (self.train_names[_idx],
                                           self.train_gt_names[_idx],
                                           self.train_targets[_idx],
                                           self.train_countries[_idx])
            
            name_processed,name_mmb = self.process_name(name)
            gt_name_processed,gt_name_mmb = self.process_name(gt_name)  
            
            return_tuple = [name,
                            name_processed.long(),
                            name_mmb.float(),
                            gt_name,
                            gt_name_processed,
                            gt_name_mmb,
                            target,
                            country]
            
        elif self.mode == 'test':
            # idx, not _idx
            name,country = (self.train_names[idx],
                                           self.test_countries[idx])
            
            name_processed,name_mmb = self.process_name(name)
            
            return_tuple = [name,
                            name_processed.long(),
                            name_mmb.float(),
                            country]            
        
        return return_tuple
    
    def process_name(self,name):
        # start with the _start_ token
        processed = [self.s2i['_start_']] * 1              

        processed.extend([self.s2i[s] 
                          if s in self.s2i
                          else self.s2i['_unk_']
                          for s in name])
        
        # add classification token for the transformer model after the end of the name
        processed.extend([self.s2i['_classify_']] * 1)         
        
        l = len(processed)
        
        if len(processed) < self.max_len:
            processed.extend([self.s2i['_pad_']] 
                             * (self.max_len - len(processed)))
        
        processed = torch.tensor(processed).squeeze()
        
        # also embed positional information and masks
        # also account for the classification token
        mmb = np.zeros((self.max_len))
        mmb[:l] = 1
        mmb = torch.from_numpy(mmb)
        
        # position information that is added to the input embeddings in the TransformerModel
        # also account for the classification token
        
        pmb = np.arange(self.vocab_len, self.vocab_len + self.max_len)
        processed = torch.stack((processed,torch.from_numpy(pmb)),dim=1)
        
        return processed,mmb
        
    def __len__(self):
        if self.mode == 'train':
            return len(self.train_idx)
        elif self.mode == 'val':
            return len(self.val_idx)
        elif self.mode == 'test':
            return len(self.test_texts)

# Launch the transformer pipeline

In [1]:
from pytorch.transformer_dataset import MisprintDataset

In [39]:
dset = MisprintDataset(add_cn_embeddings=True,mode='train')

In [36]:
tup = dset.__getitem__(4)

(name,
 name_processed,
 name_mmb,
 country) = tup

name,country

('НОВОКШОНОВА ИННА ВЛАДИМИРОВНА', 44)

In [40]:
tup = dset.__getitem__(4)

(name,
 name_processed,
 name_mmb,
 gt_name,
 gt_name_processed,
 gt_name_mmb,
 target,
 country) = tup

name,gt_name,country

('МЕДЕТБЕК КЫЗЫ МАПАБАТ', 'МЕДЕТБЕК КЫЗЫ МАХАБАТ', 34)

In [38]:
tup = dset.__getitem__(4)

(name,
 name_processed,
 name_mmb,
 gt_name,
 gt_name_processed,
 gt_name_mmb,
 target,
 country) = tup

name,gt_name,country

('КОНДРАТОВИЧ ЛЮДМИЛА АНДРЕЕВНА', 'КОНДРАТОВИЧ ЛЮДМИЛА АНДРЕЕВНА', 4)

In [30]:
dset.cn_dict

{'ANDIJON VIL': 0,
 'ARM': 1,
 'AZE': 2,
 'AZERBAIJAN': 3,
 'BLR': 4,
 'GEORGIA': 5,
 'ISRAEL': 6,
 'KAZ': 7,
 'KAZAKHSTAN': 8,
 'KGZ': 9,
 'MDA': 10,
 'MOLDOVA': 11,
 'OTHER': 12,
 'RUS': 13,
 'RUSSIAN FEDERATION': 14,
 'TJK': 15,
 'UKR': 16,
 'UZB': 17,
 'UZBEKISTAN': 18,
 'АБХАЗИЯ': 19,
 'АЗЕРБАЙДЖАН': 20,
 'АРМЕНИЯ': 21,
 'БЕЛАРУСЬ': 22,
 'ВЬЕТНАМ': 23,
 'Г. МОСКВА': 24,
 'ГРУЗИЯ': 25,
 'ДАЛЬНЕЕ ЗАРУБЕЖЬЕ': 26,
 'ИЗРАИЛЬ': 27,
 'КАЗАХСТАН': 28,
 'КАМЕРУН': 29,
 'КИРГИЗИЯ': 30,
 'КОТ-ДИВУАР': 31,
 'КР': 32,
 'КЫРГЫЗСКАЯ РЕСПУБЛИКА': 33,
 'КЫРГЫЗСТАН': 34,
 'М.О.': 35,
 'МОЛДОВА': 36,
 'МОЛДОВА, РЕСПУБЛИКА': 37,
 'НАВОИЙ': 38,
 'НАМАНГАН': 39,
 'НИГЕРИЯ': 40,
 'ПМР': 41,
 'РЕСПУБЛИКА КАЗАХСТАН': 42,
 'РОССИЙСКАЯ ФЕДЕРАЦИЯ': 43,
 'РОССИЯ': 44,
 'РТ': 45,
 'РФ': 46,
 'СЕРБИЯ': 47,
 'ТАДЖИКИСТАН': 48,
 'ТУРКМЕНИЯ': 49,
 'ТУРЦИЯ': 50,
 'УЗБЕКИСТАН': 51,
 'УКРАИНА': 52,
 'ФИЛИППИНЫ': 53,
 'ШАХРИХОН': 54}

In [27]:
dset.s2i

{' ': 0,
 "'": 1,
 '-': 2,
 '.': 3,
 'A': 4,
 'B': 5,
 'C': 6,
 'D': 7,
 'E': 8,
 'F': 9,
 'G': 10,
 'H': 11,
 'I': 12,
 'J': 13,
 'K': 14,
 'L': 15,
 'M': 16,
 'N': 17,
 'O': 18,
 'P': 19,
 'Q': 20,
 'R': 21,
 'S': 22,
 'T': 23,
 'U': 24,
 'V': 25,
 'W': 26,
 'X': 27,
 'Y': 28,
 'Z': 29,
 'Ё': 30,
 'А': 31,
 'Б': 32,
 'В': 33,
 'Г': 34,
 'Д': 35,
 'Е': 36,
 'Ж': 37,
 'З': 38,
 'И': 39,
 'Й': 40,
 'К': 41,
 'Л': 42,
 'М': 43,
 'Н': 44,
 'О': 45,
 'П': 46,
 'Р': 47,
 'С': 48,
 'Т': 49,
 'У': 50,
 'Ф': 51,
 'Х': 52,
 'Ц': 53,
 'Ч': 54,
 'Ш': 55,
 'Щ': 56,
 'Ъ': 57,
 'Ы': 58,
 'Ь': 59,
 'Э': 60,
 'Ю': 61,
 'Я': 62,
 '_start_': 63,
 '_pad_': 64,
 '_unk_': 65,
 '_classify_': 66,
 '_pos0_': 67,
 '_pos1_': 68,
 '_pos2_': 69,
 '_pos3_': 70,
 '_pos4_': 71,
 '_pos5_': 72,
 '_pos6_': 73,
 '_pos7_': 74,
 '_pos8_': 75,
 '_pos9_': 76,
 '_pos10_': 77,
 '_pos11_': 78,
 '_pos12_': 79,
 '_pos13_': 80,
 '_pos14_': 81,
 '_pos15_': 82,
 '_pos16_': 83,
 '_pos17_': 84,
 '_pos18_': 85,
 '_pos19_': 86,
 '_pos20_': 87,
 '_pos21_': 88,
 '_pos22_': 89,
 '_pos23_': 90,
 '_pos24_': 91,
 '_pos25_': 92,
 '_pos26_': 93,
 '_pos27_': 94,
 '_pos28_': 95,
 '_pos29_': 96,
 '_pos30_': 97,
 '_pos31_': 98,
 '_pos32_': 99,
 '_pos33_': 100,
 '_pos34_': 101,
 '_pos35_': 102,
 '_pos36_': 103,
 '_pos37_': 104,
 '_pos38_': 105,
 '_pos39_': 106,
 '_pos40_': 107,
 '_pos41_': 108,
 '_pos42_': 109,
 '_pos43_': 110,
 '_pos44_': 111,
 '_pos45_': 112,
 '_pos46_': 113,
 '_pos47_': 114,
 '_pos48_': 115,
 '_pos49_': 116,
 '_pos50_': 117,
 '_pos51_': 118,
 '_pos52_': 119,
 '_pos53_': 120,
 '_pos54_': 121,
 '_pos55_': 122,
 '_pos56_': 123,
 '_pos57_': 124,
 '_pos58_': 125,
 '_pos59_': 126,
 '_pos60_': 127,
 '_pos61_': 128,
 '_pos62_': 129,
 '_pos63_': 130,
 '_pos64_': 131,
 '_pos65_': 132,
 '_pos66_': 133,
 '_pos67_': 134,
 '_pos68_': 135,
 '_pos69_': 136,
 '_pos70_': 137,
 '_pos71_': 138,
 '_pos72_': 139,
 '_pos73_': 140,
 '_pos74_': 141,
 '_pos75_': 142,
 '_pos76_': 143,
 '_pos77_': 144,
 '_pos78_': 145,
 '_pos79_': 146,
 '_pos80_': 147,
 '_pos81_': 148,
 '_pos82_': 149,
 '_pos83_': 150,
 '_pos84_': 151,
 '_pos85_': 152,
 '_pos86_': 153,
 '_pos87_': 154,
 '_pos88_': 155,
 '_pos89_': 156,
 '_pos90_': 157,
 '_pos91_': 158,
 '_pos92_': 159,
 '_pos93_': 160,
 '_pos94_': 161,
 '_pos95_': 162,
 '_pos96_': 163,
 '_pos97_': 164,
 '_pos98_': 165,
 '_pos99_': 166,
 '_cn0_': 167,
 '_cn1_': 168,
 '_cn2_': 169,
 '_cn3_': 170,
 '_cn4_': 171,
 '_cn5_': 172,
 '_cn6_': 173,
 '_cn7_': 174,
 '_cn8_': 175,
 '_cn9_': 176,
 '_cn10_': 177,
 '_cn11_': 178,
 '_cn12_': 179,
 '_cn13_': 180,
 '_cn14_': 181,
 '_cn15_': 182,
 '_cn16_': 183,
 '_cn17_': 184,
 '_cn18_': 185,
 '_cn19_': 186,
 '_cn20_': 187,
 '_cn21_': 188,
 '_cn22_': 189,
 '_cn23_': 190,
 '_cn24_': 191,
 '_cn25_': 192,
 '_cn26_': 193,
 '_cn27_': 194,
 '_cn28_': 195,
 '_cn29_': 196,
 '_cn30_': 197,
 '_cn31_': 198,
 '_cn32_': 199,
 '_cn33_': 200,
 '_cn34_': 201,
 '_cn35_': 202,
 '_cn36_': 203,
 '_cn37_': 204,
 '_cn38_': 205,
 '_cn39_': 206,
 '_cn40_': 207,
 '_cn41_': 208,
 '_cn42_': 209,
 '_cn43_': 210,
 '_cn44_': 211,
 '_cn45_': 212,
 '_cn46_': 213,
 '_cn47_': 214,
 '_cn48_': 215,
 '_cn49_': 216,
 '_cn50_': 217,
 '_cn51_': 218,
 '_cn52_': 219,
 '_cn53_': 220,
 '_cn54_': 221}

In [29]:
gt_name_processed[:,2]

tensor([ 201,  201,  201,  201,  201,  201,  201,  201,  201,  201,
         201,  201,  201,  201,  201,  201,  201,  201,  201,  201,
         201,  201,  201,  201,  201,  201,  201,  201,  201,  201,
         201,  201,  201,  201,  201,  201,  201,  201,  201,  201,
         201,  201,  201,  201,  201,  201,  201,  201,  201,  201,
         201,  201,  201,  201,  201,  201,  201,  201,  201,  201,
         201,  201,  201,  201,  201,  201,  201,  201,  201,  201,
         201,  201,  201,  201,  201,  201,  201,  201,  201,  201,
         201,  201,  201,  201,  201,  201,  201,  201,  201,  201,
         201,  201,  201,  201,  201,  201,  201,  201,  201,  201])

In [7]:
gt_name_mmb

tensor([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.], dtype=torch.float64)

In [21]:
name_processed[0:31]

tensor([[ 63,  67],
        [ 43,  68],
        [ 50,  69],
        [ 47,  70],
        [ 31,  71],
        [ 49,  72],
        [ 45,  73],
        [ 33,  74],
        [ 31,  75],
        [  0,  76],
        [ 47,  77],
        [ 45,  78],
        [ 38,  79],
        [ 43,  80],
        [ 42,  81],
        [ 39,  82],
        [ 62,  83],
        [  0,  84],
        [ 43,  85],
        [ 31,  86],
        [ 49,  87],
        [ 44,  88],
        [ 31,  89],
        [ 38,  90],
        [ 31,  91],
        [ 47,  92],
        [ 45,  93],
        [ 33,  94],
        [ 44,  95],
        [ 31,  96],
        [ 66,  97]])

In [ ]:
дут()

In [15]:
name_mmb.sum()

tensor(31.)

In [31]:
len(dset.s2i)

167

In [13]:
name_processed.shape

torch.Size([100, 2])

In [10]:
name,gt_name

('МУРАТОВА РОЗМЛИЯ МАТНАЗАРОВНА', 'МУРАТОВА РОЗАЛИЯ МАТНАЗАРОВНА')

In [34]:
for key,value in dset.cn_dict.items():
    print(key,value)

ANDIJON VIL 0
ARM 1
AZE 2
AZERBAIJAN 3
BLR 4
GEORGIA 5
ISRAEL 6
KAZ 7
KAZAKHSTAN 8
KGZ 9
MDA 10
MOLDOVA 11
OTHER 12
RUS 13
RUSSIAN FEDERATION 14
TJK 15
UKR 16
UZB 17
UZBEKISTAN 18
АБХАЗИЯ 19
АЗЕРБАЙДЖАН 20
АРМЕНИЯ 21
БЕЛАРУСЬ 22
ВЬЕТНАМ 23
Г. МОСКВА 24
ГРУЗИЯ 25
ДАЛЬНЕЕ ЗАРУБЕЖЬЕ 26
ИЗРАИЛЬ 27
КАЗАХСТАН 28
КАМЕРУН 29
КИРГИЗИЯ 30
КОТ-ДИВУАР 31
КР 32
КЫРГЫЗСКАЯ РЕСПУБЛИКА 33
КЫРГЫЗСТАН 34
М.О. 35
МОЛДОВА 36
МОЛДОВА, РЕСПУБЛИКА 37
НАВОИЙ 38
НАМАНГАН 39
НИГЕРИЯ 40
ПМР 41
РЕСПУБЛИКА КАЗАХСТАН 42
РОССИЙСКАЯ ФЕДЕРАЦИЯ 43
РОССИЯ 44
РТ 45
РФ 46
СЕРБИЯ 47
ТАДЖИКИСТАН 48
ТУРКМЕНИЯ 49
ТУРЦИЯ 50
УЗБЕКИСТАН 51
УКРАИНА 52
ФИЛИППИНЫ 53
ШАХРИХОН 54